version: '3'
services:

  extends:
    file: docker-compose-routing.yml
    service: nginx

  extends:
    file: docker-compose-routing.yml
    service: common-bff

  extends:
    file: docker-compose-routing.yml
    service: mobile-bff

  extends:
    file: docker-compose-routing.yml
    service: open-bff

  extends:
    file: docker-compose-open.yml
    service: auth

  extends:
    file: docker-compose-common.yml
    service: db

  extends:
    file: docker-compose-common.yml
    service: user

networks:
  external:
    name: callme-external
    driver: bridge
  callme_internal:
    name: callme-internal
    driver: bridge