version: '3'
services:
  callme-db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USERNAME}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - callme
  auth:
    image: callme-auth:latest
    build:
      context: ./auth
      dockerfile: Dockerfile
    ports:
      - "80:8080"
    networks:
      - external
      - callme
    environment:
      INTERNAL_NETWORK: ${INTERNAL_NETWORK}
  user:
    image: callme-user:latest
    build:
      context: ./user
      dockerfile: Dockerfile
    depends_on:
      - callme-db
    networks:
      - callme
    environment:
      DATABASE_HOST: "callme-db"
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}

networks:
  external:
    driver: bridge
  callme:
    driver: bridge