version: '3'
services:

  nginx:
    image: nginx:atest
    name: callem-nginx
    restart: always
    ports:
      - "80:80"
    build:
      context: ./nginx
      dockerfile: Dockerfile
    networks:
      - external

  db:
    image: mysql:latest
    name: callme-db
    restart: always
    depends_on:
      - nginx
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USERNAME}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - callme_internal

  mobile-bff:
    image: callme-mobile-bff:latest
    name: callme-mobile-bff
    build:
      context: ./mobile-bff
      dockerfile: Dockerfile
    depends_on:
      - nginx
    networks:
      - callme_internal

  auth:
    image: callme-auth:latest
    name: callme-auth
    build:
      context: ./auth
      dockerfile: Dockerfile
    depends_on:
      - mobile-bff
    networks:
      - callme_internal

  user:
    image: callme-user:latest
    name: callme-user
    build:
      context: ./user
      dockerfile: Dockerfile
    depends_on:
      - mobile-bff
    networks:
      - callme_internal
    environment:
      DATABASE_HOST: "callme-db"
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}

networks:
  external:
    name: callme-external
    driver: bridge
  callme_internal:
    name: callme-internal
    driver: bridge