version: '3'
services:
  
  stun-turn:
    build: ./stun-turn
    container_name: callme-stun-turn
    environment:
      DATABASE_HOST: "callme-db"
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    networks:
      - external
      - callme_internal