version: '3'
services:

  nginx:
    image: nginx:latest
    container_name: callme-nginx
    restart: always
    ports:
      - "80:80"
    enviroment:
      HOST_IP: ${HOST_IP}
    build: ./nginx
    networks:
      - external
      - callme_internal

  common-bff:
    image: callme-common-bff:latest
    container_name: callme-common-bff
    build:
      context: ./common-bff
      dockerfile: Dockerfile
    networks:
      - callme_internal
      
  mobile-bff:
    image: callme-mobile-bff:latest
    container_name: callme-mobile-bff
    build:
      context: ./mobile-bff
      dockerfile: Dockerfile
    networks:
      - callme_internal

  open-bff:
    image: callme-open-bff:latest
    container_name: callme-open-bff
    build:
      context: ./open-bff
      dockerfile: Dockerfile
    networks:
      - callme_internal
