version: '3'

services:
  stun-turn:
    image: coturn/coturn
    container_name: callme-stun-turn
    environment:
      HOST_IP: ${HOST_IP}
      DATABASE_HOST: "callme-db"
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - ./stun-turn/turnserver.conf:/etc/turnserver.conf
    restart: unless-stopped
    network_mode: "host"

  push:
    image: callme-push:latest
    container_name: callme-push
    build:
      context: ./push
      dockerfile: Dockerfile
    networks:
      - callme_internal