version: '3'
services:

  nginx:
    extends:
      file: docker-compose-routing.yml
      service: nginx
    depends_on:
      - common-bff
      - mobile-bff
      - open-bff

  common-bff:
    extends:
      file: docker-compose-routing.yml
      service: common-bff
    depends_on:
      - user

  mobile-bff:
    extends:
      file: docker-compose-routing.yml
      service: mobile-bff

  open-bff:
    extends:
      file: docker-compose-routing.yml
      service: open-bff
    depends_on:
      - auth

  auth:
    extends:
      file: docker-compose-open.yml
      service: auth
    depends_on:
      - tokenization
      - turn-user

  db:
    extends:
      file: docker-compose-common.yml
      service: db

  user:
    extends:
      file: docker-compose-common.yml
      service: user
    depends_on:
      - db

  stun-turn:
    extends:
      file: docker-compose-messaging.yml
      service: stun-turn
    depends_on:
      - db

  push:
    extends:
      file: docker-compose-messaging.yml
      service: push

  turn-user:
    extends:
      file: docker-compose-common.yml
      service: turn-user
    depends_on:
      - db

  messaging-user:
    extends:
      file: docker-compose-common.yml
      service: messaging-user
    depends_on:
      - db

  tokenization:
    extends:
      file: docker-compose-common.yml
      service: tokenization

  call-manager:
    extends:
      file: docker-compose-messaging.yml
      service: call-manager

networks:
  external:
    name: callme-external
    driver: bridge
  callme_internal:
    name: callme-internal
    internal: true
    driver: bridge