version: '3'
services:

  nginx:
    extends:
      file: docker-compose-routing.yml
      service: nginx

  common-bff:
    extends:
      file: docker-compose-routing.yml
      service: common-bff

  mobile-bff:
    extends:
      file: docker-compose-routing.yml
      service: mobile-bff

  open-bff:
    extends:
      file: docker-compose-routing.yml
      service: open-bff

  auth:
    extends:
      file: docker-compose-open.yml
      service: auth

  db:
    extends:
      file: docker-compose-common.yml
      service: db

  user:
    extends:
      file: docker-compose-common.yml
      service: user

networks:
  external:
    name: callme-external
    driver: bridge
  callme_internal:
    name: callme-internal
    driver: bridge