version: '3'

services:
  stun-turn:
    container_name: callme-stun-turn
    build:
      context: ./stun-turn
      dockerfile: Dockerfile
    ports:
      - "3478:3478"
      - "3478:3478/udp"
      - "5349:5349"
      - "5349:5349/udp"
    environment:
      HOST_IP: ${HOST_IP}
      DATABASE_HOST: "callme-db"
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    restart: unless-stopped
    networks:
      - external
      - callme_internal

  push:
    image: callme-push:latest
    container_name: callme-push
    build:
      context: ./push
      dockerfile: Dockerfile
    networks:
      - callme_internal

  call-manager:
    image: callme-call-manager:latest
    container_name: callme-call-manager
    build:
      context: ./call-manager
      dockerfile: Dockerfile
    networks:
      - callme_internal