version: '3'
services:

  nginx:
    extends:
      file: docker-compose-routing.yml
      service: nginx
    depends_on:
      - common-bff
      - mobile-bff
      - open-bff

  common-bff:
    extends:
      file: docker-compose-routing.yml
      service: common-bff
    depends_on:
      - user

  mobile-bff:
    extends:
      file: docker-compose-routing.yml
      service: mobile-bff

  open-bff:
    extends:
      file: docker-compose-routing.yml
      service: open-bff
    depends_on:
      - auth

  auth:
    extends:
      file: docker-compose-open.yml
      service: auth

  db:
    extends:
      file: docker-compose-common.yml
      service: db

  user:
    extends:
      file: docker-compose-common.yml
      service: user
    depends_on:
      - db

networks:
  external:
    name: callme-external
    driver: bridge
  callme_internal:
    name: callme-internal
    driver: bridge