version: '3'

services:
  stun-turn:
    image: coturn/coturn
    environment:
      HOST_IP: ${HOST_IP}
      DATABASE_HOST: "callme-db"
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - ./stun-turn/turn.conf:/etc/turnserver.conf
    restart: unless-stopped
    network_mode: "host"
